### ISSUE TITLE
Nested frontmatter is getting the wrong formatting

### ISSUE THREAD

**Issue by uroybd** [obsidian-nvim/obsidian.nvim#58]
### 🐛 Describe the bug

Consider this frontmatter:

```md
---
log:
  - status: Read
    timestamp: 2024-11-05T18:58:25+06:00
  - status: In Progress
    timestamp: 2024-10-27T17:00:09+06:00
  - status: Read
    timestamp: 2023-12-05T01:05:08+06:00
  - status: In Progress
    timestamp: 2023-10-24T20:59:49+06:00
  - status: Read
    timestamp: 2022-11-07T00:00:00+06:00
  - status: Read
    timestamp: 2021-11-06T00:00:00+06:00
  - status: Read
    timestamp: 2020-11-06T00:00:00+06:00
  - status: To Read
    timestamp: 2017-09-30T00:00:00+06:00
---
```

On save, it is being formatted as:

```
---
log:
  - status: "Read timestamp: 2024-11-05T18:58:25+06:00"
  - status: "In Progress timestamp: 2024-10-27T17:00:09+06:00"
  - status: "Read timestamp: 2023-12-05T01:05:08+06:00"
  - status: "In Progress timestamp: 2023-10-24T20:59:49+06:00"
  - status: "Read timestamp: 2022-11-07T00:00:00+06:00"
  - status: "Read timestamp: 2021-11-06T00:00:00+06:00"
  - status: "Read timestamp: 2020-11-06T00:00:00+06:00"
  - status: "To Read timestamp: 2017-09-30T00:00:00+06:00"
---
```

### Config

```lua
local M = {
  "obsidian-nvim/obsidian.nvim",
  version = "*",
  lazy = true,
  ft = "markdown",
  dependencies = {
    -- Required.
    "nvim-lua/plenary.nvim",
    "saghen/blink.cmp",
    -- see below for full list of optional dependencies 👇
  },
}

function get_timestamp()
  -- get ISO 8601 timestamp with offset
  return os.date "%Y-%m-%dT%H:%M:%S+06:00"
end

function M.config()
  require("obsidian").setup {
    ui = { enable = false },
    workspaces = {

      {
        name = "The Codex",
        path = "~/Documents/The Codex/",
      },
    },
    notes = "Scratchpad",
    completion = {
      blink = true,
    },
    mappings = {
      -- Overrides the 'gf' mapping to work on markdown/wiki links within your vault.
      ["gf"] = {
        action = function()
          return require("obsidian").util.gf_passthrough()
        end,
        opts = { noremap = false, expr = true, buffer = true },
      },
      -- Toggle check-boxes.
      ["<leader>ch"] = {
        action = function()
          return require("obsidian").util.toggle_checkbox()
        end,
        opts = { buffer = true },
      },
      -- Smart action depending on context: follow link, show notes with tag, or toggle checkbox.
      ["<cr>"] = {
        action = function()
          return require("obsidian").util.smart_action()
        end,
        opts = { buffer = true, expr = true },
      },
    },
    wiki_link_func = "prepend_note_path",
    note_frontmatter_func = function(note)
      -- Add the title of the note as an alias.
      if note.title then
        note:add_alias(note.title)
      end
      local timestamp = get_timestamp()
      note:add_field("updated", timestamp)
      if note.get_field "created" == nil then
        note:add_field("created", timestamp)
      end

      local out = { aliases = note.aliases, tags = note.tags }

      -- `note.metadata` contains any manually added fields in the frontmatter.
      -- So here we just make sure those fields are kept in the frontmatter.
      if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
        for k, v in pairs(note.metadata) do
          out[k] = v
        end
      end

      return out
    end,
  }
end

return M
```

### Environment

```sh
$ nvim --version
NVIM v0.11.0
Build type: Release
LuaJIT 2.1.1744318430
Run "nvim -V1 -v" for more info
```

```sh
$ nvim --headless -c 'lua require("obsidian").info()' -c q
Obsidian.nvim v3.10.0 (e0eb92c5afcacf5bf11e4735079a538fd1486ea9)
Status:
  • buffer directory: nil
  • working directory: /Users/meghnaad/Documents/The Codex
Workspaces:
  ✓ active workspace: Workspace(name='The Codex', path='/Users/meghnaad/Documents/The Codex', root='/Users/meghnaad/Documents/The Codex')
Dependencies:
  ✓ plenary.nvim: 857c5ac632080dba10aae49dba902ce3abf91b35
  ✓ blink.cmp: cb5e346d9e0efa7a3eee7fd4da0b690c48d2a98e
Integrations:
  ✓ picker: SnacksPicker()
  ✓ completion: enabled (blink) ✓ refs, ✓ tags, ✓ new
    all sources:
      • Snippets
      • LSP
      • obsidian
      • obsidian_new
      • Buffer
      • Path
      • Omni
      • obsidian_tags
      • Cmdline
Tools:
  ✓ rg: ripgrep 14.1.1
Environment:
  • operating system: Darwin
Config:
  • notes_subdir: nil
```
